// Generated by https://quicktype.io

export interface InstaFeedResponse {
    num_results:                    number;
    more_available:                 boolean;
    auto_load_more_enabled:         boolean;
    is_direct_v2_enabled:           boolean;
    next_max_id:                    string;
    view_state_version:             string;
    client_feed_changelist_applied: boolean;
    request_id:                     string;
    pull_to_refresh_window_ms:      number;
    preload_distance:               number;
    status:                         string;
    hide_like_and_view_counts:      number;
    last_head_load_ms:              number;
    feed_items:                     FeedItem[];
}

export interface FeedItem {
    media_or_ad: MediaOrAd;
}

export interface MediaOrAd {
    taken_at:                                   number;
    pk:                                         string;
    id:                                         string;
    device_timestamp:                           number;
    media_type:                                 number;
    code:                                       string;
    client_cache_key:                           string;
    filter_type:                                number;
    accessibility_caption?:                     string;
    is_unified_video:                           boolean;
    should_request_ads:                         boolean;
    caption_is_edited:                          boolean;
    like_and_view_counts_disabled:              boolean;
    commerciality_status:                       CommercialityStatus;
    is_paid_partnership:                        boolean;
    is_visual_reply_commenter_notice_enabled:   boolean;
    original_media_has_visual_reply_media:      boolean;
    comment_likes_enabled:                      boolean;
    comment_threading_enabled:                  boolean;
    has_more_comments:                          boolean;
    max_num_visible_preview_comments:           number;
    preview_comments:                           any[];
    comments:                                   any[];
    can_view_more_preview_comments:             boolean;
    comment_count:                              number;
    hide_view_all_comment_entrypoint:           boolean;
    inline_composer_display_condition:          InlineComposerDisplayCondition;
    image_versions2?:                           MediaOrAdImageVersions2;
    original_width?:                            number;
    original_height?:                           number;
    user:                                       MediaOrAdUser;
    can_viewer_reshare:                         boolean;
    like_count:                                 number;
    has_liked:                                  boolean;
    top_likers:                                 string[];
    facepile_top_likers:                        UserElement[];
    photo_of_you:                               boolean;
    is_organic_product_tagging_eligible:        boolean;
    can_see_insights_as_brand:                  boolean;
    preview?:                                   string;
    caption:                                    Caption | null;
    comment_inform_treatment:                   CommentInformTreatment;
    sharing_friction_info:                      SharingFrictionInfo;
    can_viewer_save:                            boolean;
    is_in_profile_grid:                         boolean;
    profile_grid_control_enabled:               boolean;
    organic_tracking_token:                     string;
    has_shared_to_fb:                           number;
    product_type:                               string;
    deleted_reason:                             number;
    integrity_review_decision:                  IntegrityReviewDecision;
    music_metadata:                             MusicMetadata | null;
    inventory_source:                           InventorySource;
    is_seen:                                    boolean;
    is_eof:                                     boolean;
    ranking_weight:                             number;
    title?:                                     string;
    nearly_complete_copyright_match?:           boolean;
    media_cropping_info?:                       MediaCroppingInfo;
    thumbnails?:                                Thumbnails;
    igtv_exists_in_viewer_series?:              boolean;
    is_post_live?:                              boolean;
    liker_config?:                              LikerConfig;
    mashup_info?:                               MashupInfo;
    is_dash_eligible?:                          number;
    video_dash_manifest?:                       string;
    video_codec?:                               string;
    number_of_qualities?:                       number;
    video_versions?:                            VideoVersion[];
    has_audio?:                                 boolean;
    video_duration?:                            number;
    view_count?:                                number;
    carousel_media_count?:                      number;
    carousel_media?:                            CarouselMedia[];
    video_subtitles_confidence?:                number;
    video_subtitles_uri?:                       string;
    usertags?:                                  Usertags;
    play_count?:                                number;
    clips_metadata?:                            ClipsMetadata;
    main_feed_carousel_starting_media_id?:      string;
    main_feed_carousel_has_unseen_cover_media?: boolean;
}

export interface Caption {
    pk:                   string;
    user_id:              number;
    text:                 string;
    type:                 number;
    created_at:           number;
    created_at_utc:       number;
    content_type:         ContentType;
    status:               Status;
    bit_flags:            number;
    did_report_as_spam:   boolean;
    share_enabled:        boolean;
    user:                 UserElement;
    is_covered:           boolean;
    media_id:             string;
    private_reply_status: number;
    has_translation?:     boolean;
}

export enum ContentType {
    Comment = "comment",
}

export enum Status {
    Active = "Active",
}

export interface UserElement {
    pk:                   number;
    username:             string;
    full_name:            string;
    is_private:           boolean;
    profile_pic_url:      string;
    profile_pic_id:       string;
    is_verified:          boolean;
    follow_friction_type: number;
    growth_friction_info: GrowthFrictionInfo;
    account_badges:       any[];
}

export interface GrowthFrictionInfo {
    has_active_interventions: boolean;
    interventions:            Interventions;
}

export interface Interventions {
}

export interface CarouselMedia {
    id:                     string;
    media_type:             number;
    image_versions2:        CarouselMediaImageVersions2;
    original_width:         number;
    original_height:        number;
    accessibility_caption?: string;
    pk:                     string;
    carousel_parent_id:     string;
    commerciality_status:   CommercialityStatus;
    video_versions?:        VideoVersion[];
    video_duration?:        number;
    is_dash_eligible?:      number;
    video_dash_manifest?:   string;
    video_codec?:           string;
    number_of_qualities?:   number;
}

export enum CommercialityStatus {
    NotCommercial = "not_commercial",
}

export interface CarouselMediaImageVersions2 {
    candidates: FirstFrame[];
}

export interface FirstFrame {
    width:  number;
    height: number;
    url:    string;
}

export interface VideoVersion {
    type:   number;
    width:  number;
    height: number;
    url:    string;
    id:     string;
}

export interface ClipsMetadata {
    music_info:                        null;
    original_sound_info:               OriginalSoundInfo;
    audio_type:                        string;
    music_canonical_id:                string;
    featured_label:                    null;
    mashup_info:                       MashupInfo;
    nux_info:                          null;
    viewer_interaction_settings:       null;
    branded_content_tag_info:          BrandedContentTagInfo;
    shopping_info:                     null;
    additional_audio_info:             AdditionalAudioInfo;
    is_shared_to_fb:                   boolean;
    breaking_content_info:             null;
    challenge_info:                    null;
    reels_on_the_rise_info:            null;
    breaking_creator_info:             null;
    asset_recommendation_info:         null;
    contextual_highlight_info:         null;
    clips_creation_entry_point:        string;
    audio_ranking_info:                AudioRankingInfo;
    template_info:                     null;
    is_fan_club_promo_video:           null;
    disable_use_in_clips_client_cache: boolean;
}

export interface AdditionalAudioInfo {
    additional_audio_username: null;
    audio_reattribution_info:  AudioReattributionInfo;
}

export interface AudioReattributionInfo {
    should_allow_restore: boolean;
}

export interface AudioRankingInfo {
    best_audio_cluster_id: string;
}

export interface BrandedContentTagInfo {
    can_add_tag: boolean;
}

export interface MashupInfo {
    mashups_allowed:                          boolean;
    can_toggle_mashups_allowed:               boolean;
    has_been_mashed_up:                       boolean;
    formatted_mashups_count:                  null;
    original_media:                           null;
    non_privacy_filtered_mashups_media_count: null;
    mashup_type:                              null;
    is_creator_requesting_mashup:             boolean;
}

export interface OriginalSoundInfo {
    audio_asset_id:                    number;
    music_canonical_id:                null;
    progressive_download_url:          string;
    dash_manifest:                     string;
    ig_artist:                         UserElement;
    should_mute_audio:                 boolean;
    original_media_id:                 string;
    hide_remixing:                     boolean;
    duration_in_ms:                    number;
    time_created:                      number;
    original_audio_title:              string;
    consumption_info:                  ConsumptionInfo;
    allow_creator_to_rename:           boolean;
    can_remix_be_shared_to_fb:         boolean;
    formatted_clips_media_count:       null;
    audio_parts:                       any[];
    is_explicit:                       boolean;
    original_audio_subtype:            string;
    is_audio_automatically_attributed: boolean;
}

export interface ConsumptionInfo {
    is_bookmarked:                 boolean;
    should_mute_audio_reason:      string;
    is_trending_in_clips:          boolean;
    should_mute_audio_reason_type: null;
}

export interface CommentInformTreatment {
    should_have_inform_treatment: boolean;
    text:                         string;
    url:                          null;
    action_type:                  null;
}

export interface MediaOrAdImageVersions2 {
    candidates:             FirstFrame[];
    additional_candidates?: AdditionalCandidates;
}

export interface AdditionalCandidates {
    igtv_first_frame: FirstFrame;
    first_frame:      FirstFrame;
}

export enum InlineComposerDisplayCondition {
    ImpressionTrigger = "impression_trigger",
}

export enum IntegrityReviewDecision {
    Pending = "pending",
    Rejected = "rejected",
}

export enum InventorySource {
    MediaOrAd = "media_or_ad",
}

export interface LikerConfig {
    is_daisy:                       boolean;
    hide_view_count:                boolean;
    show_count_in_likers_list:      boolean;
    show_view_count_in_likers_list: boolean;
    show_daisy_liker_list_header:   boolean;
    show_learn_more:                boolean;
    ads_display_mode:               number;
    display_mode:                   number;
    disable_liker_list_navigation:  boolean;
    show_author_view_likes_button:  boolean;
    is_in_daisy_controls:           boolean;
}

export interface MediaCroppingInfo {
    square_crop?: SquareCrop;
}

export interface SquareCrop {
    crop_left:   number;
    crop_right:  number;
    crop_top:    number;
    crop_bottom: number;
}

export interface MusicMetadata {
    music_canonical_id:  string;
    audio_type:          null | string;
    music_info:          null;
    original_sound_info: OriginalSoundInfo | null;
}

export interface SharingFrictionInfo {
    should_have_sharing_friction: boolean;
    bloks_app_url:                null;
    sharing_friction_payload:     null;
}

export interface Thumbnails {
    video_length:                   number;
    thumbnail_width:                number;
    thumbnail_height:               number;
    thumbnail_duration:             number;
    sprite_urls:                    string[];
    thumbnails_per_row:             number;
    total_thumbnail_num_per_sprite: number;
    max_thumbnails_per_sprite:      number;
    sprite_width:                   number;
    sprite_height:                  number;
    rendered_width:                 number;
    file_size_kb:                   number;
}

export interface MediaOrAdUser {
    pk:                             number;
    username:                       string;
    full_name:                      string;
    is_private:                     boolean;
    profile_pic_url:                string;
    profile_pic_id:                 string;
    friendship_status:              FriendshipStatus;
    is_verified:                    boolean;
    follow_friction_type:           number;
    growth_friction_info:           GrowthFrictionInfo;
    account_badges:                 any[];
    has_anonymous_profile_picture:  boolean;
    is_unpublished:                 boolean;
    is_favorite:                    boolean;
    has_highlight_reels:            boolean;
    has_primary_country_in_feed:    boolean;
    has_primary_country_in_profile: boolean;
    transparency_product_enabled:   boolean;
    fan_club_info:                  FanClubInfo;
    latest_reel_media:              number;
}

export interface FanClubInfo {
    fan_club_id:   null;
    fan_club_name: null;
}

export interface FriendshipStatus {
    following:        boolean;
    outgoing_request: boolean;
    is_muting_reel:   boolean;
    is_bestie:        boolean;
    is_restricted:    boolean;
    is_feed_favorite: boolean;
}

export interface Usertags {
    in: In[];
}

export interface In {
    user:                       UserElement;
    position:                   number[];
    start_time_in_video_in_sec: null;
    duration_in_video_in_sec:   null;
}
